language: scala
dist: bionic
sudo: true
script: sbt ++$TRAVIS_SCALA_VERSION 'test'
scala:
  - 2.13.2
jdk:
  - oraclejdk9
services: mongodb
before_script:
  - sleep 15
  - sudo chmod +x /usr/local/bin/sbt
